### ISSUE TITLE
Allow copy and paste into credentials window

### ISSUE THREAD

**Issue by dylankbuckley** [dylankbuckley/monzo-menubar-macos#3]
Currently can't paste credentials into the NSTextFields. Quick google hasn't come up with solution. Need to dig a bit deeper.

**Comment by dylankbuckley** [comment]
This seems to be because we have to manually assign keyboard gestures to the fields. Right clicking and pasting works fine.

**Comment by dylankbuckley** [comment]
Fixed!

**Comment by thomashorrobin** [comment]
I'm obviously late to this but I've pulled your changed and it's working much smoother now 👍
