### ISSUE TITLE
Locally store the credentials. 

### ISSUE THREAD

**Issue by dylankbuckley** [dylankbuckley/monzo-menubar-macos#4]
Probably getting to the stage where it's going to be easier to build a little oauth server to do authentication properly. Regardless we should probably persist current auth data.

**Comment by thomashorrobin** [comment]
yeah I'm thinking that to. Atm I'm basically just never closing the app, which isn't an ideal solution

**Comment by dylankbuckley** [comment]
A crude fix for this has been done in #5
