### ISSUE TITLE
Number formatting issue

### ISSUE THREAD

**Issue by dylankbuckley** [dylankbuckley/monzo-menubar-macos#6]
<img width="219" alt="screen shot 2018-07-02 at 11 58 06" src="https://user-images.githubusercontent.com/8408005/42160467-39a5644c-7def-11e8-9c45-8e5b13e12fc2.png">

£2.4 vs £2.40

**Comment by thomashorrobin** [comment]
also, if you've spent £0 it shows up as a negitive which annoys me ever so slightly but not enough for me to actually fix it lol

**Comment by dylankbuckley** [comment]
Ah I buy a coffee every morning before I look at my computer so I have never seen this haha
